### ISSUE TITLE
Instant crash in iOS simulator iPhone 12 - please help

### ISSUE THREAD

**Issue by daveshirman** [MrJai/flutter_to_airplay#16] opened 2021-07-19 13:49 UTC
First of all thanks for this!

So I'm just trying to either:

1) Use better_player - as I was already doing - then show the airplay cast widget.

OR

2) Use your native player widget in place of better_player - which has the airplay icon built-in.

e.g.
```
  Widget _buildvideoPlayer(Video video) {
    if (Platform.isIOS) {
      return FlutterAVPlayerView(
        urlString: widget.video.videoM3u8,
      );
    }

    // Otherwise on Android - load different player.

    return AspectRatio(
      aspectRatio: 16 / 9,
      child: BetterPlayer(
        controller: _betterVideoController!,
      ),
    );
  }
}
```

Both instantly crash the simulator.

Can you provide at least a minimum code example in-context of how to use your two widgets please?

Thank you.

**Comment by MrJai** [comment] 2021-07-26 05:37
@daveshirman Thank you for reporting this. I had a very busy week so couldn't check this.

Let me try your code snippet and get back to you.

**Comment by daveshirman** [comment] 2021-07-26 10:47
No problem at all. I am happy to donate to your funding if it helps you
spend some time improving the docs/bugs as this is an excellent feature if
working.
Thank you.

**Comment by MrJai** [comment] 2021-08-05 11:55
@daveshirman I am working on this issue today. But I am unable to reproduce the crash you mentioned. Can you please share some code snippets that will cause the crash?

Also, I noticed that you are asking, for example, I have added the example in the project, and one case is added by default where the video is being loaded from a URL, whereas the other case is commented out where a video can be loaded from assets.

https://github.com/MrJai/flutter_to_airplay/blob/46904f383ff464e04b21f1ddd255129ce3822a95/example/lib/main.dart


Please let me know if you want me to cover more cases in the example project. Please feel free to share if you want some more features in this plugin as well.

**Comment by daveshirman** [comment] 2021-08-05 12:07
Thank you so much for your reply.
I really didn't do anything but set it up as per your original example,
perhaps I missed something, like an important step in the setup on iOS
Xcode project?

I will try to run the plugin again today and reply to you hear.

Thank you and please tell me where I can donate to keep you funded! Put a
button on your GitHub if you haven't already. You deserve it.

**Comment by MrJai** [comment] 2021-08-05 13:36
Thank you @daveshirman, I have just added some more examples on the basis of the frequently asked uses cases.

For donations, you can buy me as many coffees as you want, because being a developer I convert caffeine to code :P

<a href="https://www.buymeacoffee.com/junaidR" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>

**Comment by daveshirman** [comment] 2021-08-05 17:02
I am no longer seeing this instant crash,  I can't tell you what is different, but I can successfully launch the`AirPlayRoutePickerView` now.

Question I guess (having not used this before), is can I use that to mirror the app in general, whilst using my own video player, or do I have to use that widget in conjunction with the `FlutterAVPlayerView` in order to mirror video content within my app?

Thank you so much, donation coming your way as soon as I've got this release build done!

**Comment by MrJai** [comment] 2021-08-05 17:26
yes you can use it with any player.

**Comment by daveshirman** [comment] 2021-08-05 17:46
Thanks, so if using just the `AirPlayRoutePickerView `, does it mirror the whole app?
Also - did you see my error I pasted above? Looks like a simple layout problem is my guess?

**Comment by MrJai** [comment] 2021-08-06 05:16
Yes, that is intentional behaviour, because I am just providing a control, users can customise its appearance as per their app's UI. I will document it in the next version.

**Comment by MrJai** [comment] 2021-08-07 01:05
Thank you @daveshirman for coffees.

I think we can close this issue now? You can always open new issue, or reach out to me via twitter at @Rana_Jai.

**Closed** 2021-08-07 01:05 UTC

**Comment by daveshirman** [comment] 2021-08-07 01:27
You're welcome. I think as long as the documentation explains that if you
don't supply a wrapping widget with dimensions, it will crash, then yeah.
Cheers.

**Comment by MrJai** [comment] 2021-08-07 14:15
Hi Dave, I just updated the package and its changelog as well. Now the widget comes wrapped around in a 44 x 44 container, but its width and height are customizable, and users can change it as per their need/design requirements. It is also documented both in Changelog and in widget documentation.
